### ISSUE TITLE
Inspiracje

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/_mojePanstwo-Portal#738]

**Comment by KrzysztofMadejski** [comment]
Inspiracja od Code for South Africa podrzucona przez Marka Jagielskiego:

> Przykład trochę na czasie dla nas, a z RPA:
    + portal: https://openbylaws.org.za/za-jhb/act/by-law/2011/air-pollution-control/
    + metadata: https://openbylaws.org.za/za-jhb/act/by-law/2011/air-pollution-control/resources/
    + API: https://indigo.openbylaws.org.za/api/documents/57.json
    + źródło Akoma 2.0: https://indigo.openbylaws.org.za/api/za-jhb/act/by-law/2011/air-pollution-control/eng.xml

> Tak sobie wyobrażałem serwis. To jest dla mnie poprzeczka. About: https://openbylaws.org.za/about.html

**Comment by KrzysztofMadejski** [comment]
Dla mnie poprzeczką jest https://www.govtrack.us/

- overview ustawy: https://www.govtrack.us/congress/bills/115/hr7
- ustawa zmieniająca https://www.govtrack.us/congress/bills/115/hr72/text
- porównywanie zmian: https://www.govtrack.us/congress/bills/115/hr7/text#compare=ih

**Comment by michalskop** [comment]
French laws, very detailed application with different versions of the laws + info from the parliament, custom data format (jsons):
https://www.regardscitoyens.org/gitlaw-how-the-law-factory-turns-the-french-parliamentary-process-into-300-version-controlled-open-data-visualizations/
Examples:
overview of laws: http://www.lafabriquedelaloi.fr/lois.html
1 law: http://www.lafabriquedelaloi.fr/articles.html?loi=pjl15-nouvelles_libertes_entreprises_actifs
parliamentary debates 1 law: http://www.lafabriquedelaloi.fr/debats.html?loi=pjl12-489&etape=01_1%C3%A8relecture_assemblee_commission

German laws: (abandoned) github project, using markdown for texts and yaml for metadata:
http://okfnlabs.org/blog/2012/12/13/bundesgit-german-laws-on-github.html
github: https://github.com/bundestag/gesetze

Czech laws:  comercial project, includes inner and outer links, html only (probably against scraping), versions (paid)
https://www.zakonyprolidi.cz/
example of 1 law: https://www.zakonyprolidi.cz/cs/1999-106

Slovak laws: comercial project, includes inner and outer links, html only (probably against scraping), versions (paid)
http://www.zakonypreludi.sk/
example of 1 law: http://www.zakonypreludi.sk/zz/2005-300

(Czecho)Slovak laws: official site, include inner nad outer links, versions, html only (but scrapable easily), some charting
Example 1 law: https://www.slov-lex.sk/pravne-predpisy/SK/ZZ/1948/87/vyhlasene_znenie.html

Slovak legislative process: official site (only since 2016)
example 1 bill: https://www.slov-lex.sk/legislativne-procesy/SK/LP/2016/893

British laws: official, versions
http://www.legislation.gov.uk/
example 1 bill, section: http://www.legislation.gov.uk/ukpga/1998/29/section/7

**Comment by KrzysztofMadejski** [comment]
Przerzucone na drive: https://docs.google.com/document/d/1xaYug3LF3DOnXxcOKHUs46yyeEINNV7D1239tftGFWE/edit#heading=h.5brc0p3hogy0
